### ISSUE TITLE
Media Queries For Height Fail on Devices

### ISSUE THREAD

**Issue by nicopierson** [nicopierson/yourcity#64]
## Tasks
- [x] height for mobile: vh for sections don't add to 100
- [x] margin above main section does not line with navbar
- [x] use overflow auto to remove horizontal and vertical scroll bars
